// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoyzzrnquhdzgecpxahx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhveXp6cm5xdWhkemdlY3B4YWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjM2MjcsImV4cCI6MjA2NTM5OTYyN30.lYnj3UAic9V7MimmKU5HUAcjk3WrnHbj7MMkwDFSsvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);